PUT http://localhost/wp-json/custom/v1/ask/community/  
Authorization: Basic bW9oYW1lZC50QGlsbGltaXRpcy5jb206Q2FsbG1lMjAwMi4=
Content-Type: application/json

 {
    "user_id":3,
    "community_id":2156,
    "text_question": "What is the goal"
}

